name: JIRA release

author: steven.jeong

description: Automate JIRA release

inputs:
  githubToken:
    description: Github Token that has access to `repo`
    required: true
  jiraHost:
    description: Jira host address
    required: true
  jiraEmail:
    description: Jira email
    required: true
  jiraApiToken:
    description: Jira api token
    required: true
  jiraProjectKey:
    description: Jira project key
    required: true
  jiraVersionPrefix:
    description: Jira version prefix
    required: true
  jiraReleaseVersion:
    description: Jira release version
    required: true
  jiraIssueDoneStatusName:
    description: Jira issue status name that represents `Done`
    default: 'Done'
  shouldRelease:
    description: Whether the jira version should be released automatically
    default: true

runs:
  using: 'node16'
  main: 'lib/index.js'

branding:
  icon: 'list'
  color: 'purple'
